// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftCraft.Infrastructure.Data;

#nullable disable

namespace ShiftCraft.Infrastructure.Migrations.EF
{
    [DbContext(typeof(ShiftCraftDbContext))]
    [Migration("20251222205210_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShiftCraft.Domain.Entities.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Businesses", (string)null);
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.CoreStaffRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<int>("DayTypeId")
                        .HasColumnType("int");

                    b.Property<int>("MinCoreStaffCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("DayTypeId");

                    b.ToTable("CoreStaffRules", (string)null);
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.DayType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DayTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Weekday"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Weekend"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Holiday"
                        });
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCoreStaff")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeeklyMaxMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.EmployeeRole", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("EmployeeRoles", (string)null);
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Supervisor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Worker"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Trainee"
                        });
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.RuleViolation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("RuleCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("ViolationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeeklyScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("WeeklyScheduleId");

                    b.ToTable("RuleViolations", (string)null);
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.ScheduleDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayTypeId")
                        .HasColumnType("int");

                    b.Property<int>("WeeklyScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DayTypeId");

                    b.HasIndex("WeeklyScheduleId");

                    b.ToTable("ScheduleDays", (string)null);
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.ShiftAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleDayId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoleId");

                    b.HasIndex("ScheduleDayId");

                    b.HasIndex("ShiftTemplateId");

                    b.ToTable("ShiftAssignments", (string)null);
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.ShiftRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<int>("DayTypeId")
                        .HasColumnType("int");

                    b.Property<int>("RequiredCount")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("DayTypeId");

                    b.HasIndex("RoleId");

                    b.HasIndex("ShiftTemplateId");

                    b.ToTable("ShiftRequirements", (string)null);
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.ShiftTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("ShiftTemplates", (string)null);
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.WeeklySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("WeeklySchedules", (string)null);
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.WorkRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSevenDaysOpen")
                        .HasColumnType("bit");

                    b.Property<int>("MaxDailyMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MinWeeklyOffDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("WorkRules", (string)null);
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.CoreStaffRule", b =>
                {
                    b.HasOne("ShiftCraft.Domain.Entities.Business", "Business")
                        .WithMany("CoreStaffRules")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ShiftCraft.Domain.Entities.DayType", "DayType")
                        .WithMany("CoreStaffRules")
                        .HasForeignKey("DayTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("DayType");
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.Employee", b =>
                {
                    b.HasOne("ShiftCraft.Domain.Entities.Business", "Business")
                        .WithMany("Employees")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.EmployeeRole", b =>
                {
                    b.HasOne("ShiftCraft.Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftCraft.Domain.Entities.Role", "Role")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.RuleViolation", b =>
                {
                    b.HasOne("ShiftCraft.Domain.Entities.Employee", "Employee")
                        .WithMany("RuleViolations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ShiftCraft.Domain.Entities.WeeklySchedule", "WeeklySchedule")
                        .WithMany("RuleViolations")
                        .HasForeignKey("WeeklyScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("WeeklySchedule");
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.ScheduleDay", b =>
                {
                    b.HasOne("ShiftCraft.Domain.Entities.DayType", "DayType")
                        .WithMany("ScheduleDays")
                        .HasForeignKey("DayTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ShiftCraft.Domain.Entities.WeeklySchedule", "WeeklySchedule")
                        .WithMany("ScheduleDays")
                        .HasForeignKey("WeeklyScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayType");

                    b.Navigation("WeeklySchedule");
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.ShiftAssignment", b =>
                {
                    b.HasOne("ShiftCraft.Domain.Entities.Employee", "Employee")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ShiftCraft.Domain.Entities.Role", "Role")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ShiftCraft.Domain.Entities.ScheduleDay", "ScheduleDay")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("ScheduleDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftCraft.Domain.Entities.ShiftTemplate", "ShiftTemplate")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("ShiftTemplateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");

                    b.Navigation("ScheduleDay");

                    b.Navigation("ShiftTemplate");
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.ShiftRequirement", b =>
                {
                    b.HasOne("ShiftCraft.Domain.Entities.Business", "Business")
                        .WithMany("ShiftRequirements")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ShiftCraft.Domain.Entities.DayType", "DayType")
                        .WithMany("ShiftRequirements")
                        .HasForeignKey("DayTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ShiftCraft.Domain.Entities.Role", "Role")
                        .WithMany("ShiftRequirements")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ShiftCraft.Domain.Entities.ShiftTemplate", "ShiftTemplate")
                        .WithMany("ShiftRequirements")
                        .HasForeignKey("ShiftTemplateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("DayType");

                    b.Navigation("Role");

                    b.Navigation("ShiftTemplate");
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.ShiftTemplate", b =>
                {
                    b.HasOne("ShiftCraft.Domain.Entities.Business", "Business")
                        .WithMany("ShiftTemplates")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.WeeklySchedule", b =>
                {
                    b.HasOne("ShiftCraft.Domain.Entities.Business", "Business")
                        .WithMany("WeeklySchedules")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.WorkRule", b =>
                {
                    b.HasOne("ShiftCraft.Domain.Entities.Business", "Business")
                        .WithMany("WorkRules")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.Business", b =>
                {
                    b.Navigation("CoreStaffRules");

                    b.Navigation("Employees");

                    b.Navigation("ShiftRequirements");

                    b.Navigation("ShiftTemplates");

                    b.Navigation("WeeklySchedules");

                    b.Navigation("WorkRules");
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.DayType", b =>
                {
                    b.Navigation("CoreStaffRules");

                    b.Navigation("ScheduleDays");

                    b.Navigation("ShiftRequirements");
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeRoles");

                    b.Navigation("RuleViolations");

                    b.Navigation("ShiftAssignments");
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.Role", b =>
                {
                    b.Navigation("EmployeeRoles");

                    b.Navigation("ShiftAssignments");

                    b.Navigation("ShiftRequirements");
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.ScheduleDay", b =>
                {
                    b.Navigation("ShiftAssignments");
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.ShiftTemplate", b =>
                {
                    b.Navigation("ShiftAssignments");

                    b.Navigation("ShiftRequirements");
                });

            modelBuilder.Entity("ShiftCraft.Domain.Entities.WeeklySchedule", b =>
                {
                    b.Navigation("RuleViolations");

                    b.Navigation("ScheduleDays");
                });
#pragma warning restore 612, 618
        }
    }
}
